### ISSUE TITLE
When you edit a post, the edit styling takes over the 'reply' styling 

### ISSUE THREAD

**Issue by zachha** [zachha/Code-With-Us#29]
The edit styling and the markdown of the post that was being edited stays in the 'reply' box even if you minimize the reply drawer, needs to be reset to reply on minimize and/or a cancel edit button

**Comment by HarryCaveMan** [comment]
I will add a button to reset it but will have the default be for it to remain. I left it this way in order to allow users to more easily read old posts to reference them.

**Comment by HarryCaveMan** [comment]
I've got a working prototype of the reset button, a few finishing touches and some styling and I'll prepare for a PR. I also went through and changed the components that depended on the `user` object to instead depend on `user.isLoggedIn`.
